name: Build and Deploy

on:
 push:
  branches:
   - main # Измените на вашу основную ветку

jobs:
 build-deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
      node-version: 17 # Измените версию Node.js, если необходимо

   - name: Install dependencies
     run: npm install

   - name: Build application
     run: npm run build # Измените на команду сборки вашего приложения

   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist
